baseURL = "https://galdebert.github.io/"
languageCode = "en-us"
title = "Guillaume Aldebert's Blog"
#theme = "ananke"
theme = "galdebert-hyde"
disqusShortname = "https-galdebert-github-io"
#googleAnalytics = "Your tracking code"

[params]
themeColor = "theme-base-0d"
description = "mostly dev"
copyright = "Guillaume Aldebert. All rights reserved."